### ISSUE TITLE
preserveDanglingCloseParenthesis confusion

### ISSUE THREAD

**Issue by Synesso** [scala-ide/scalariform#154] opened 2016-02-17 22:45 UTC
- documented as `danglingCloseParenthesis`, but `formatterPreferences.properties` has key `preserveDanglingCloseParenthesis`
- documented with values `Prevent` or `Force`, but `formatterPreferences.properties` sets it to `false`
- marked as deprecated in 0.1.5 & using v0.1.6 the property doesn't have any effect with any combination of key `(preserveD|d)anglingCloseParenthesis` and value `Prevent/Force | false/true`
- I have no idea how to prevent dangling close parens. Scalariform 0.1.6 always reformats to dangling.
- I don't wish to dangle.

**Comment by fommil** [comment] 2016-02-17 22:56
can you create a test case for `Prevent` ? We accepted a unit test with that change and it seemed to do exactly what you want.

**Comment by Synesso** [comment] 2016-02-18 00:00
I created a test case and the formatter does what I expect. It is behaving differently from the CLI, so maybe pref parsing is the trouble? I use `danglingCloseParenthesis=prevent`.

**Comment by jkinkead** [comment] 2016-03-07 15:51
I can't reproduce with a fresh build of the CLI. How are you running the CLI?

Also, what does the log message say it's running with? If you're running against a file, it should print something like:
```
Formatting with preferences: SpaceInsideParentheses -> false,
IndentPackageBlocks -> true, MaxArrowIndent -> 40, ...
```

**Comment by Synesso** [comment] 2016-03-09 07:09
*$ cat dev/fmt*
#!/bin/bash

dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

opts=''
opts="$opts $SCALARIFORM_OPTS"
opts="$opts --preferenceFile=$dir/scalariform.properties"

if [ "$#" -gt 0 ]; then
  opts="$opts $@"
else
  opts="$opts --recurse $dir/../src/main/scala/"
  opts="$opts --recurse $dir/../src/test/scala/"
fi

scalariform $opts



*$ cat dev/scalariform.properties*
alignParameters=false
alignArguments=false
alignSingleLineCaseStatements=false
compactControlReadability=false
compactStringConcatenation=false
doubleIndentClassDeclaration=true
formatXml=true
indentLocalDefs=false
indentPackageBlocks=true
indentSpaces=2
indentWithTabs=false
multilineScaladocCommentsStartOnFirstLine=false
placeScaladocAsterisksBeneathSecondAsterisk=false
preserveSpaceBeforeArguments=false
danglingCloseParenthesis=prevent
rewriteArrowSymbols=false
spaceBeforeColon=false
spaceInsideBrackets=false
spaceInsideParentheses=false
spacesWithinPatternBinders=true
spacesAroundMultiImports=false



*$ dev/fmt*
Assuming source is Scala 2.11.6
Formatting with preferences: PlaceScaladocAsterisksBeneathSecondAsterisk ->
false, SpaceInsideParentheses -> false, IndentPackageBlocks -> true,
IndentWithTabs -> false, SpaceInsideBrackets -> false,
CompactStringConcatenation -> false, SpaceBeforeColon -> false, FormatXml
-> true, CompactControlReadability -> false, SpacesWithinPatternBinders ->
true, IndentSpaces -> 2, SpacesAroundMultiImports -> false, IndentLocalDefs
-> false, MultilineScaladocCommentsStartOnFirstLine -> false,
PreserveSpaceBeforeArguments -> false, AlignArguments -> false,
AlignSingleLineCaseStatements -> false, AlignParameters -> false,
DoubleIndentClassDeclaration -> true, RewriteArrowSymbols -> false

**Comment by jkinkead** [comment] 2016-03-09 15:52
It looks like you must be using an older version of scalariform. What is printed out if you run using the `-version` flag?

Version `0.1.8` should have this fixed, if you upgrade.

**Comment by Synesso** [comment] 2016-03-10 06:49
Brew version is at 0.1.6. Can the formula be updated to latest stable? For
now I'll use --HEAD

**Comment by Synesso** [comment] 2016-03-10 06:52
Trouble building head:

*$ brew install --HEAD scalariform*
==> Cloning https://github.com/daniel-trinh/scalariform.git
Updating /Library/Caches/Homebrew/scalariform--git
==> Checking out branch master
==> sbt project cli assembly
Last 15 lines from /Users/jem/Library/Logs/Homebrew/scalariform/01.sbt:
at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
at sbt.Execute.work(Execute.scala:235)
at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
at
sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
[error] (scalariform/*:update) java.lang.IllegalArgumentException: Cannot
add dependency 'org.scala-lang#scala-compiler;2.10.6' to configuration
'ensime-internal' of module org.scalariform#scalariform_2.10;0.1.8 because
this configuration doesn't exist!
[error] (cli/*:projectDescriptors) java.lang.IllegalArgumentException:
Cannot add dependency 'org.scala-lang#scala-compiler;2.10.6' to
configuration 'ensime-internal' of module
org.scalariform#scalariform_2.10;0.1.8 because this configuration doesn't
exist!
[error] Total time: 0 s, completed 10/03/2016 4:49:06 PM

**Comment by kflorence** [comment] 2017-07-05 02:15
I'm also having trouble with this using `sbt-scalariform` 1.6.0:

```scala
    Card(
      name = Messages("bootstrap.index.page.components.button"),
      groups = List(
        ComponentGroup(
          name = Messages("bootstrap.index.page.components.button.styles"),
          examples = ButtonStyles.values.toList.map(style =>
            button.map(_.copy(buttonStyle = style)).content(style.toString))
        )
      )
    )
```
even though I have `.setPreference(DanglingCloseParenthesis, Force)`, it refuses to let the closing `)` in the `examples = ButtonStyles.values.toList.map(style =>` line dangle.

**Comment by godenji** [comment] 2017-07-13 22:38
@kflorence it works with braces but not parens. 

For now you'll either have to go without dangling parens in sub expressions, or convert to uses braces (not ideal I know, like you I tend to go with parens in these situations).

Feel free to dig into the library internals and issue a PR if you find the culprit.

**Closed** 2017-08-04 15:51 UTC
