### ISSUE TITLE
Dot-less method call with type argument triggers parser error

### ISSUE THREAD

**Issue by Taig** [scala-ide/scalariform#148] opened 2016-02-11 10:14 UTC
````scala
object Test {
    implicit class Enrich( v: Any ) {
        def foo[T]( t: T ) = ???
    }

    // Works fine
    3 foo "bar"

    // Triggers warning
    3 foo[String] "bar"
}
````

````
> compile
[info] Formatting 1 Scala source ...
[warn] Scalariform parser error for ./Test.scala: Expected token SEMI but got Token(LBRACKET,[,158,[)
````

**Comment by jkinkead** [comment] 2016-03-07 15:26
Duplicate of #163 .

**Closed by jkinkead** 2016-03-07 15:26 UTC
