### ISSUE TITLE
options to align case statements and variable definitions

### ISSUE THREAD

**Issue by sschaef** [scala-ide/scalariform#170] opened 2016-02-18 22:10 UTC
_From @fommil on August 30, 2015 14:53_

currently scalariform only supports aligning single line case statements, eg.

``` scala
case foo: Foo => ...
case bar         => ...
```

but it would be good if there was an option for multi line cases and also if there was a similar thing for variable definitions. At the very least, an option not to reformat the location of the `=` for variable definitions would be good.

_Copied from original issue: daniel-trinh/scalariform#76_

**Comment by godenji** [comment] 2017-10-25 23:23
Duplicate of #70

**Closed by godenji** 2017-10-25 23:23 UTC
