### ISSUE TITLE
please transfer to group organisation

### ISSUE THREAD

**Issue by fommil** [scala-ide/scalariform#137] opened 2015-10-23 10:06 UTC
Hi Matt,

It is quite confusing that there are now two repositories hosting the tickets and pull requests for scalariform (both yours and @daniel-trinh), and even though there is a clarifying note on the README, it is still confusing people (plus really hard to see the full set of open tickets).

As Scalariform is of interest to many people (it's still a really critical part of scala-ide, ensime and many builds and I know several organisations who cannot upgrade scala-ide until some regressions are fixed in scalariform), it would be really good if the repository was hosted at a single location and owned by several people with shared responsibility.

Would you be interested in transferring ownership of this repo to a group such as `scala-ide` or `ensime`? We would, of course, give you full admin rights. This would also allow us to:

1. consolidate the issue trackers and pull requests from multiple repositories
2. add additional maintainers to the repository to take responsibility for pull requests, merging and the build (both myself and Daniel initially, possibly also @dragos if he's interested)

I'm personally keen to get a good integration test environment set up using the ENSIME testing hardware infrastructure, so that we can catch formatting regressions on large projects before cutting releases.

If this is something you're interested in, please let us know. The process is to:

1. go to settings and then "Transfer" to one of the owners of `ensime` (e.g. me, rory, aemon, edani) (although if you'd rather trust to transfer to @dragos or @daniel-trinh, that's also fine)
2. wait for it to appear at `github.com/ensime/scalariform` then fork it back to your user account

this will preserve the full history of everything and your contributions / stars will still show up under your github profile. We've done this with pretty much all the repos on ENSIME and its worked out to be great for everybody.

Best regards,
Sam

**Comment by fommil** [comment] 2015-10-23 10:51
@daniel-trinh in the meantime, perhaps we should just go ahead with moving your repo over to `ensime`? That way we'll have half the tickets / PRs and we can do Matt's later if he agrees to this.

**Comment by fommil** [comment] 2015-12-02 08:58
I've discussed this with @daniel-trinh @dragos @sschaef and @hseeberger and in the new year `scala-ide` will become the new home of `scalariform` and `sbt` will, once again, be the owner of `sbt-scalariform`.

Unfortunately, since @mdr has not responded to any requests, we'll transfer daniel's repo / PRs / issue tracker to `scala-ide`. Perhaps we can ask github to give that repo higher precedence in search but the best we can do is comment an all tickets here and ask the reporter to close the ticket and resubmit on the maintained repo.

There is no easy workaround at the moment, but you may be lucky enough to be able to force a specific version of scalariform in your sbt build config.

**Comment by xevix** [comment] 2015-12-08 05:06
@fommil Given this move, where should issues be reported between now and moving to scala-ide? My case is more of a question/feature request regarding enforcing camelCase, not a bug, but I don't want it forgotten.

**Comment by daniel-trinh** [comment] 2015-12-08 05:08
Since we're going to be moving the issues on this tracker over to wherever it ends up anyway, I think adding it into this tracker is fine.

**Comment by daniel-trinh** [comment] 2015-12-08 05:09
I suppose we'll start by moving either my or mdr's tracker, and then the other and remove duplicate issues.. unless there's a better way that I am not aware of yet?

**Comment by fommil** [comment] 2015-12-08 06:48
We'll be moving tickets from Daniel's tracker but there is bugger all we can do about this tracker unless Matt returns.

**Comment by xevix** [comment] 2015-12-08 10:57
Understood, I've added the issue in Daniel's tracker. Thanks!

**Closed** 2016-01-11 15:32 UTC
