### ISSUE TITLE
Keep single case on its line

### ISSUE THREAD

**Issue by stanch** [scala-ide/scalariform#85] opened 2013-07-14 01:23 UTC
Hi,

I would like to preserve (or ideally force) this kind of layout with a single ```case```:
```scala
future {
  // ...
} onSuccess { case result ⇒
  // ...
}
```
rather than
```scala
future {
  // ...
} onSuccess {
  case result ⇒
    // ...
}
```

This is similar to how ```scalariform``` treats lambdas, and saves space and indentation. Two ```case```s should of course be put each on its line. Common scenarios besides ```onSuccess```/```onFailure``` include ```zip```+```map``` combinations, etc.

Please note that this is related to, but different from #82.

Kind regards,
Nick

**Comment by jkinkead** [comment] 2016-03-07 17:42
Duplicate of #29 . This would be nice. :)

**Closed by jkinkead** 2016-03-07 17:42 UTC
