### ISSUE TITLE
Option request: align case alternatives like single-line arguments

### ISSUE THREAD

**Issue by sschaef** [scala-ide/scalariform#172] opened 2016-02-18 22:10 UTC
_From @acjay on July 15, 2015 19:9_

For code that looks like:

```
(option1, option2) match {
  case (Some(Object(_, "property value")), _) |
    (None, None)                                       => 5
  case (None, Some(Object(_, "other property value"))) => 6
  case _                                               => 7
}
```

It gets rewritten to:

```
(option1, option2) match {
  case (Some(Object(_, "property value")), _) |
    (None, None) => 5
  case (None, Some(Object(_, "other property value"))) => 6
  case _                                               => 7
}
```

It would be nice to have the option to have case statements with multi-line LHS to still have their RHS aligned

_Copied from original issue: daniel-trinh/scalariform#71_

**Comment by godenji** [comment] 2017-10-25 23:25
Duplicate of #70 (or at least same principle, align arrows of multline case statements)

**Closed by godenji** 2017-10-25 23:25 UTC
