### ISSUE TITLE
Issue line/column information with parsing errors

### ISSUE THREAD

**Issue by sschaef** [scala-ide/scalariform#204] opened 2016-03-01 15:46 UTC
_From @jrudolph on March 1, 2016 15:40_

That would simplify debugging quite a bit :)

_Copied from original issue: daniel-trinh/scalariform#114_

**Comment by jkinkead** [comment] 2016-03-08 03:45
Duplicate of #104 . Although this would be pretty awesome.

**Closed by jkinkead** 2016-03-08 03:45 UTC

**Comment by jrudolph** [comment] 2016-03-08 08:22
Ah, yes, sorry for missing that one.
