### ISSUE TITLE
Incorrect indentation produced

### ISSUE THREAD

**Issue by thesamet** [scala-ide/scalariform#221] opened 2016-03-30 22:45 UTC
Running the CLI with -alignParameters +doubleIndentClassDeclaration -preserveDanglingCloseParenthesis

```
-  case class MyClass(a: String,
-                                 b: String,
-                                 c: Option[String]) extends Foo {
+  case class MyClass(
+    a: String,
+      b: String,
+      c: Option[String]
+) extends Foo {
```

The problem is that the "a: String" line gets two spaces and not 4, as it should due to the +doubleIndentClassDeclaration.

Update: this happens when the above case class is nested with a class. Here is a failing unit test:

```
  {
    implicit val formattingPreferences =
        FormattingPreferences.setPreference(AlignParameters, false)
        .setPreference(DoubleIndentClassDeclaration, true)

    """object Foo {
      |  case class Bar(alpha: String,
      |                 beta: String,
      |                 gamma: String) extends Baz {
      |  }
      |}""" ==>
    """object Foo {
      |  case class PersonSignUpRequest(
      |      alpha: String,
      |      beta: String,
      |      gamma: String) extends Baz {
      |  }
      |}"""
  }
```

**Comment by jkinkead** [comment] 2016-06-14 22:19
Thanks for the bug report!

This is fixed on `master` (duplicate of #187 ).

**Closed by jkinkead** 2016-06-14 22:19 UTC
