### ISSUE TITLE
Allow space in front of ":" used in a context bound

### ISSUE THREAD

**Issue by hseeberger** [scala-ide/scalariform#49] opened 2012-05-14 09:13 UTC
In a context bound the colon should be prefixed with a space, e.g.:

```
def foo[A : Manifest] = ...
```

But scalariform will always treat is like a colon in a type annotation, so the above will be formatted without space:

```
def foo[A: Manifest] = ...
```

**Comment by jkinkead** [comment] 2016-03-07 17:35
Duplicate of #135 .

**Closed by jkinkead** 2016-03-07 17:35 UTC
