### ISSUE TITLE
support format ArrowAssoc similar to alignSingleLineCaseStatements

### ISSUE THREAD

**Issue by sschaef** [scala-ide/scalariform#184] opened 2016-02-18 22:15 UTC
_From @giabao on March 21, 2014 7:42_

``` scala
val m = Map(
  "a" -> 1,
  "bb" -> 2,
  "ccc" -> 3
)
```

is formatted as:

``` scala
val m = Map(
  "a"   -> 1,
  "bb"  -> 2,
  "ccc" -> 3
)
```

_Copied from original issue: daniel-trinh/scalariform#17_

**Comment by sschaef** [comment] 2016-02-18 22:15
_From @acjay on July 14, 2015 18:17_

This would be great for overall consistency

**Comment by ches** [comment] 2016-05-28 09:25
It seems either this or #109 can be closed as a duplicate.

**Comment by godenji** [comment] 2017-07-14 16:37
Duplicate of #109

**Closed by godenji** 2017-07-14 16:37 UTC
